spring:
   profiles:
      active:
        - dev
---
server:
  port: 8201

spring:
  profiles: dev
  application:
      name: microconfig-test-client666

eureka:
 client:
  service-url:
    defaultZone: http://admin:enjoy@localhost:7301/eureka
    
info:
  app.name: microcloud-config-client-dev
  company.name: enjoy666
---
server:
  port: 8102

spring:
  profiles: beta
  application:
      name: microconfig-test-client2

eureka:
 client:
  service-url:
    defaultZone: http://admin:enjoy@localhost:7301/eureka
    
info:
  app.name: microcloud-config-client-dev
  company.name: enjoy
