spring:
  profiles:
    active:
      - dev
---
server:
  port: 8201

spring:
  profiles: dev
  application:
    name: microconfig-test-client2
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.jdbc.Driver # 配置MySQL的驱动程序类
    url: jdbc:mysql://120.24.178.171:3306/evaluate?serverTimezone=GMT%2B8 # 数据库连接地址
    username: root # 数据库用户名
    password: root1234% # 数据库连接密码

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:enjoy@localhost:7301/eureka
    register-with-eureka: true

info:
  app.name: microcloud-config-client-dev
  company.name: enjoy
---
server:
  port: 8102

spring:
  profiles: beta
  application:
    name: microconfig-test-client2

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:enjoy@eureka1:7001/eureka
    register-with-eureka: true
  
info:
  app.name: microcloud-config-client-beta
  company.name: enjoybeta

